### ISSUE TITLE
tty: true being lost

### ISSUE THREAD

**Issue by internalsystemerror** [nohaapav/swarmpit#305]
When I edit a stack config and add to a service: ```tty: true```, this is saved, remembered and used correctly. However, when I then reedit that same stack config, the latest yml has lost the tty: true flag, so unless manually entering it again, when clicking deploy it's lost.

It is supported: https://docs.docker.com/v17.12/docker-cloud/apps/stack-yaml-reference/#single-value-keys-analogous-to-a-docker-run-counterpart

**Comment by lumir-mrkva** [comment]
@internalsystemerror thanks for reporting, we're indeed ignoring this property

**Comment by internalsystemerror** [comment]
Thanks, loving this app btw, fine job.

If I can contribute the fix, just point me in the right direction
